# =========================================
# Docker Compose Core pour les Services Essentiels
# =========================================
version: '3.8'

services:
  # KAFKA STACK
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    env_file:
      - ./config/zookeeper.env
    ports:
      - "2181:2181"
    networks:
      - my_network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    env_file:
      - ./config/kafka.env
    ports:
      - "9092:9092"
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 5

  # HADOOP NAMENODE
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode_hadoop
    # restart: always
    ports:
      - 9870:9870
      - 8020:8020
    volumes:
      - namenode_data:/hadoop/dfs/name
    env_file:
      - ./config/namenode.env
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "hdfs dfsadmin -report || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # HADOOP DATANODE
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode_hadoop
    # restart: always
    depends_on:
      namenode:
        condition: service_healthy
    ports:
      - 9864:9864
    volumes:
      - datanode_data:/hadoop/dfs/data
    env_file:
      - ./config/datanode.env
    networks:
      - my_network

  # SPARK STACK
  spark:
    image: bitnami/spark:3.3.1
    container_name: spark
    env_file:
      - ./config/spark.env
    ports:
      - "4040:4040"
      - "8090:8080"
    depends_on:
      namenode:
        condition: service_healthy
    volumes:
      - ./collecte/api/py_spark:/opt/airflow/py_spark
      - ./collecte/api/py_spark:/app
      - ./collecte/api/kafka:/opt/airflow/kafka
    networks:
      - my_network

volumes:
  namenode_data:
  datanode_data:

networks:
  my_network:
    external: true

    