# =========================================
# Docker Compose Stack Airflow
# =========================================
version: '3.8'

services:
  airflow-postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_db
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom_airflow:latest
    container_name: airflow_init
    user: "0:0"
    depends_on:
      airflow-postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow_db
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com
      "
    volumes:
      - ./collecte/api/airflow/dags:/opt/airflow/dags
      - ./collecte/api/airflow/logs:/opt/airflow/logs
      - ./collecte/api/kafka:/opt/airflow/kafka
      - ./collecte/api/py_spark:/opt/airflow/py_spark
      - ./collecte/api:/opt/airflow/scripts
    networks:
      - my_network

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_webserver
    image: custom_airflow:latest
    user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      airflow-postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow_db
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
    volumes:
      - ./collecte/api/airflow/dags:/opt/airflow/dags
      - ./collecte/api/airflow/logs:/opt/airflow/logs
      - ./collecte/api/kafka:/opt/airflow/kafka
      - ./collecte/api/py_spark:/opt/airflow/py_spark
      - ./collecte/api:/opt/airflow/scripts
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - my_network
    restart: unless-stopped

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom_airflow:latest
    container_name: airflow_scheduler
    user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      airflow-postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow_db
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
    volumes:
      - ./collecte/api/airflow/dags:/opt/airflow/dags
      - ./collecte/api/airflow/logs:/opt/airflow/logs
      - ./collecte/api/kafka:/opt/airflow/kafka
      - ./collecte/api/py_spark:/opt/airflow/py_spark
      - ./collecte/api:/opt/airflow/scripts
    command: scheduler
    networks:
      - my_network
    restart: unless-stopped

volumes:
  airflow_postgres_data:

networks:
  my_network:
    external: true